# Generated by Django 5.0.6 on 2024-07-13 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
